os:
  - linux
  - osx

language: python

os:
 - linux
 - windows

python:
  - '2.6'
  - '2.7'

env:
  - TOX_ENV=default
  - TOX_ENV=faulty_javahome

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq openjdk-7-jdk openjdk-7-jre ant
  - pip install tox

script:
  - tox -e $TOX_ENV
