# docs: https://github.com/marketplace/actions/close-stale-issues?version=v9.0.0

name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9

